[GIT PULL] Add compile-time and run-time version check API
axboe/liburing pull request #741
Opened 2022-11-30 23:57 UTC by chergert

Pretty standard API additions for shared library version checking at both compile-time and run-time.

Adds the following to the ABI for runtime checks:

```
int io_uring_major_version (void);
int io_uring_minor_verison (void);
bool io_uring_check_version(int major, int minor);
```

Adds the following to the API for compile time checks:

```
#define IO_URING_CHECK_VERSION(major,minor) ...
#define IO_URING_VERSION_MAJOR ...
#define IO_URING_VERSION_MINOR ...
```

A new `io_uring_version.h` header is installed next to `compat.h` and generated similarly in `configure`.

Includes some basic tests as well.

The only sort of "wizardry" here is that we use a not-so-common trick to parse `Makefile.common` with `make` to extract the values of `$VERSION_MAJOR` and `$VERSION_MINOR`. (I've been doing this in the GNOME Builder IDE to extract compiler flags for a very, very long time).

Fixes #736

----
## git request-pull output:
```
The following changes since commit 919755a7d0096fda08fb6d65ac54ad8d0fe027cd:

  Add test cases for eventfd and epoll loops (2022-11-30 10:53:09 -0700)

are available in the Git repository at:

  git@github.com:chergert/liburing.git master

for you to fetch changes up to 537107c807e9d307e337cc9495a0efb051b8e350:

  version: add runtime and compile time version checks (2022-11-30 15:52:55 -0800)

----------------------------------------------------------------
Christian Hergert (3):
      Makefile.common: include VERSION_MINOR from specfile
      version: generate io_uring_version.h from Makefile.common
      version: add runtime and compile time version checks

 .gitignore             |  1 +
 Makefile.common        |  1 +
 configure              | 16 ++++++++++++++++
 src/Makefile           |  4 +++-
 src/include/liburing.h | 19 +++++++++++++++++++
 src/version.c          | 21 +++++++++++++++++++++
 test/Makefile          |  1 +
 test/version.c         | 25 +++++++++++++++++++++++++
 8 files changed, 87 insertions(+), 1 deletion(-)
 create mode 100644 src/version.c
 create mode 100644 test/version.c

```
----
## By submitting this pull request, I acknowledge that:
* [x] I have followed the above pull request guidelines.
* [x] I have the rights to submit this work under the same license.
* [x] I agree to a Developer Certificate of Origin (see https://developercertificate.org for more information).

2022-12-01 03:07 UTC, ammarfaizi2 requested changes
Since you export 3 new functions.

You need add them into the liburing.map as well.

2022-12-01 03:07 UTC, ammarfaizi2 commented on src/include/liburing.h
> +bool io_uring_check_version (int major, int minor);
Please remove the space between the function name and arguments list.

2022-12-01 03:07 UTC, ammarfaizi2 commented on src/version.c
> +}
Please remove the space between the function name and arguments list.

2022-12-01 16:08 UTC, axboe commented
It's the echo -e, sh doesn't support that. I wonder how that worked for you?

2022-12-01 16:12 UTC, axboe commented
Following incremental makes it work for me:

```
diff --git a/configure b/configure
index 6f444eb96767..82636bb8aa30 100755
--- a/configure
+++ b/configure
@@ -429,9 +429,10 @@ echo "CXX=$cxx" >> $config_host_mak
 print_config "CXX" "$cxx"
 
 # generate io_uring_version.h
+ECHO=$(which echo)
 MAKE_PRINT_VARS="include Makefile.common\nprint-%: ; @echo \$(\$*)\n"
-VERSION_MAJOR=$(echo -e "$MAKE_PRINT_VARS" | make -s -f - print-VERSION_MAJOR)
-VERSION_MINOR=$(echo -e "$MAKE_PRINT_VARS" | make -s -f - print-VERSION_MINOR)
+VERSION_MAJOR=$($ECHO -e "$MAKE_PRINT_VARS" | make -s -f - print-VERSION_MAJOR)
+VERSION_MINOR=$($ECHO -e "$MAKE_PRINT_VARS" | make -s -f - print-VERSION_MINOR)
 io_uring_version_h="src/include/liburing/io_uring_version.h"
 cat > $io_uring_version_h << EOF
 /* SPDX-License-Identifier: MIT */
 ```

2022-12-01 16:13 UTC, axboe commented
This is probably better:

```
diff --git a/configure b/configure
index 6f444eb96767..7d8dbf86f322 100755
--- a/configure
+++ b/configure
@@ -430,8 +430,8 @@ print_config "CXX" "$cxx"
 
 # generate io_uring_version.h
 MAKE_PRINT_VARS="include Makefile.common\nprint-%: ; @echo \$(\$*)\n"
-VERSION_MAJOR=$(echo -e "$MAKE_PRINT_VARS" | make -s -f - print-VERSION_MAJOR)
-VERSION_MINOR=$(echo -e "$MAKE_PRINT_VARS" | make -s -f - print-VERSION_MINOR)
+VERSION_MAJOR=$(env echo -e "$MAKE_PRINT_VARS" | make -s -f - print-VERSION_MAJOR)
+VERSION_MINOR=$(env echo -e "$MAKE_PRINT_VARS" | make -s -f - print-VERSION_MINOR)
 io_uring_version_h="src/include/liburing/io_uring_version.h"
 cat > $io_uring_version_h << EOF
 /* SPDX-License-Identifier: MIT */
 ```

2022-12-01 16:15 UTC, axboe commented
With that folded in, I think the only missing piece is a man page for the version helpers.

2022-12-01 19:33 UTC, chergert commented
Pulled in the `env ` addition for echo and rebased, along with adding man pages for the functions and macros.

Thanks for the review!

2022-12-01 19:37 UTC, merged

2022-12-01 19:37 UTC, axboe commented
Thanks! Pulled.

2023-12-24 05:59 UTC, YoSTEALTH commented
Thanks @chergert  for added these functions. https://github.com/axboe/liburing/issues/418

Just curious why the functions name starts with `io_uring_*` shouldn't it be `liburing_*` or `uring_*`